### ISSUE TITLE
Can I use the library on the main thread?

### ISSUE THREAD

**Issue by xeoneux** [ryohey/wavelet#11]
Hi @ryohey 

Although this library is simply perfect for my use case, I can easily import custom soundfonts to play different instruments, there's still a bit of latency while using postMessage to send data about the note that is to be played by the audio worklet.

Is there a way to run this library on the main thread without using postMessage?

**Comment by xeoneux** [comment]
Hi @ryohey, any solution for this?

**Comment by ryohey** [comment]
@xeoneux Hi, AudioWorklets cannot run on the main thread. I think the latency may be caused by another part. Can I see your source code?

**Comment by ryohey** [comment]
I realize this is nice for testing purpose in some situations. We can use ScriptProcessorNode to run on the main thread by adding `export * from "./processor/SynthProcessorCore"` to `lib/src/index.ts`.

```ts
    let frame = 0
    const synth = new SynthProcessorCore(context.sampleRate, () => frame)
    const synthNode = context.createScriptProcessor(256, 0, 2)
    synthNode.onaudioprocess = (e) => {
      const buf0 = e.outputBuffer.getChannelData(0)
      const buf1 = e.outputBuffer.getChannelData(1)
      synth.process([buf0, buf1])
      frame += synthNode.bufferSize
    }
    synthNode.connect(context.destination)
```

**Comment by page200** [comment]
Hi, I'm trying to understand this discussion. Is latency in fact reduced by running on the main thread? Can it be even further reduced by implementing an option to not use AudioWorklets?

(I'm hereby also tagging @mk-pmb, who might be interested in low-latency MIDI playback as well.)

**Comment by ryohey** [comment]
Hi @page200 
> Is latency in fact reduced by running on the main thread?

I don't think so, you can measure the difference in latency when using createScriptProcessor versus AudioWorklet, and the time taken for postMessage. It would be a good resource for everyone.

For my MIDI application signal, which is the main use of wavelet, I don't have any plans to do anything in particular about latency, since I don't get many requests from people about latency.

If you could give me a little more context, I might be able to give you some advice.

**Comment by page200** [comment]
> If you could give me a little more context, I might be able to give you some advice.

Thank you. :) I would like to playback MIDI songs in the browser. Also when the window is in the background or while the user performs some actions. (For example, other libraries I tried have interruptions in the playback.) So I'd like to understand whether something (for example the latency discussed in this issue) noticeably disrupts the rhythm of the song.

If playback of songs is smooth, it would be great if you could document in the readme how to get started and run the example (run `rollup` with certain arguments? When I open `example/public/index.html`, I get `GET wavelet/example/public/js/index.js net::ERR_FILE_NOT_FOUND` in the console) and what data formats are being used under the hood for SoundFonts (for example, are only the notes that will play rendered from an SF2 file into FLAC or WAV data as JS variables in advance?).
