### ISSUE TITLE
Load multiple soundfont samples

### ISSUE THREAD

**Issue by xeoneux** [ryohey/wavelet#9]
Hi @ryohey 
This is one great library to play SoundFont files written in TypeScript.
Is there a way I can load multiple sf2 files for different instruments? Like a different one for grand piano and a different one for acoustic guitar?

**Comment by ryohey** [comment]
Yes!

In example script, all instruments from the soundfont are fed to wavelet by `postSynthMessage`.
https://github.com/ryohey/wavelet/blob/main/example/src/index.ts#L48

You can load several soundfonts and select specific instruments instead of that.
It will probably look something like this.

```typescript
    const soundFontData1 = await (await fetch("foo.sf2")).arrayBuffer()
    const soundFontData2 = await (await fetch("bar.sf2")).arrayBuffer()

    const samples1 = getSamplesFromSoundFont(
      new Uint8Array(soundFontData1),
      context
    )

    const samples2 = getSamplesFromSoundFont(
      new Uint8Array(soundFontData2),
      context
    )

    // load all instruments but piano from foo.sf2
    for (const sample of samples1) {
      if (sample.bank === 0 && sample.instrument === 0) {
         continue
      }
      postSynthMessage(
        sample,
        [sample.sample.buffer]
      )
    }

    // load piano from bar.sf2
    for (const sample of samples2) {
      if (sample.bank !== 0 || sample.instrument !== 0) {
         continue
      }
      postSynthMessage(
        sample,
        [sample.sample.buffer]
      )
    }
```

**Comment by xeoneux** [comment]
Thanks for a quick reply @ryohey, I'll try that out :smile:

**Comment by xeoneux** [comment]
Works well, thanks @ryohey
